/**
 * 设计提醒：原创桌面邮件工作台，使用顶部导航、多标签栏、文件夹树、操作工具栏与邮件列表的通用结构；
 * 不使用真实邮件服务名称、标志、账号或完整视觉资产，全部文字内容来自 mailScenario.ts。
 */
import { MAIL_SCENARIO_CONFIG } from "@/config/mailScenario";
import { Archive, ChevronDown, FileText, FolderArchive, Inbox, Mail, MailOpen, MoreHorizontal, PenLine, Search, Settings2, Star, Trash2, Users } from "lucide-react";

export function MailDesktopHeader({ activeTab = "收件箱", onAction }: { activeTab?: string; onAction?: (label: string) => void }) {
  return <><div className="flex min-w-[760px] items-center gap-5 border-b border-[#d9e3ef] bg-white px-5 py-3"><div className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-md bg-[#2b70c9] font-mono text-xs font-bold text-white">企</span><div><p className="font-sans text-base font-bold tracking-tight text-[#1c5caa]">{MAIL_SCENARIO_CONFIG.productName}</p><p className="font-mono text-[8px] tracking-[.12em] text-[#8b9db2]">{MAIL_SCENARIO_CONFIG.productSubtitle}</p></div></div><div className="h-5 w-px bg-[#dce5ef]" /><button type="button" onClick={() => onAction?.("账号菜单")} className="flex items-center gap-1.5 font-sans text-sm text-[#304a68]"><span className="grid h-5 w-5 place-items-center rounded bg-[#e8eff8] text-[9px] font-bold text-[#2c68b8]">企</span><span>{MAIL_SCENARIO_CONFIG.accountAddress}</span><ChevronDown className="h-3.5 w-3.5 text-[#7c91aa]" /></button><nav className="flex items-center gap-5 font-sans text-sm text-[#3f546b]">{MAIL_SCENARIO_CONFIG.navigationItems.map((item) => <button type="button" onClick={() => onAction?.(item)} key={item} className={item === "收件箱" ? "font-semibold text-[#1f65b6]" : ""}>{item}</button>)}</nav><div className="ml-auto flex items-center gap-3"><button type="button" onClick={() => onAction?.("搜索邮件")} className="flex w-48 items-center gap-2 border border-[#d9e2ed] bg-[#f7f9fc] px-3 py-1.5 text-[#93a4b5]"><Search className="h-3.5 w-3.5" /><span className="font-sans text-xs">搜索邮件</span></button><button type="button" onClick={() => onAction?.("个人中心")} className="grid h-7 w-7 place-items-center rounded-full bg-[#e6effd] font-mono text-[10px] font-bold text-[#2a64ad]">演</button></div></div><div className="flex min-w-[760px] items-end border-b border-[#bed4f0] bg-[#edf4ff] px-4 pt-2">{MAIL_SCENARIO_CONFIG.tabs.map((tab) => <button type="button" onClick={() => onAction?.(tab)} key={tab} className={`flex items-center gap-2 border-x border-t px-5 py-2.5 font-sans text-sm ${tab === activeTab ? "border-[#84aae2] bg-[#4c8dec] text-white" : "border-transparent bg-[#e2edfd] text-[#335679]"}`}><span>{tab}</span>{tab !== "收件箱" && <span className="text-[10px] opacity-65">×</span>}</button>)}<div className="ml-auto pb-2 pr-2 text-[10px] text-[#7390b1]">教学工作台 · 非真实邮箱服务</div></div></>;
}

export function MailDesktopSidebar({ onAction }: { onAction?: (label: string) => void }) {
  const folders = [[Inbox, "收件箱", true], [Star, "星标邮件"], [MailOpen, "待办邮件"], [Archive, "草稿箱"], [Mail, "已发送"], [Trash2, "已删除"], [FolderArchive, "项目资料"], [FolderArchive, "归档邮件"]] as const;
  return <aside className="w-[186px] shrink-0 border-r border-[#dce5ee] bg-[#fbfcfe] p-3"><button type="button" onClick={() => onAction?.("写邮件")} className="flex w-full items-center justify-center gap-2 rounded-sm bg-[#4b8def] px-3 py-2.5 font-sans text-sm font-semibold text-white shadow-sm"><PenLine className="h-4 w-4" /> 写邮件</button><div className="mt-4 space-y-0.5">{folders.map(([Icon, label, active]) => <button type="button" onClick={() => onAction?.(label)} key={label} className={`flex w-full items-center gap-2 px-2.5 py-2 text-left font-sans text-xs ${active ? "border-l-2 border-[#4b8def] bg-[#eaf3ff] font-bold text-[#2a67b7]" : "text-[#566d84] hover:bg-[#f2f6fb]"}`}><Icon className="h-3.5 w-3.5" />{label}{active && <span className="ml-auto rounded-full bg-[#4b8def] px-1.5 py-0.5 text-[8px] text-white">1</span>}</button>)}</div><div className="mt-5 border-t border-[#e2e8ef] pt-4"><p className="px-2.5 font-mono text-[9px] tracking-[.12em] text-[#8b9bab]">其他工具</p><div className="mt-2 space-y-0.5"><button type="button" onClick={() => onAction?.("邮件追踪")} className="flex w-full items-center gap-2 px-2.5 py-2 text-left font-sans text-xs text-[#687f94] hover:bg-[#f2f6fb]"><Users className="h-3.5 w-3.5" />邮件追踪</button><button type="button" onClick={() => onAction?.("设置中心")} className="flex w-full items-center gap-2 px-2.5 py-2 text-left font-sans text-xs text-[#687f94] hover:bg-[#f2f6fb]"><Settings2 className="h-3.5 w-3.5" />设置中心</button></div></div></aside>;
}

export function ConfigurableMailWorkbench({ onOpen }: { onOpen: () => void }) {
  const { inbox, routineMessages } = MAIL_SCENARIO_CONFIG;
  const totalMessages = routineMessages.length + 1;
  return <div className="mail-client overflow-x-auto border border-[#cad8e8] bg-white shadow-[0_18px_38px_rgba(35,72,112,.10)]"><div className="min-w-[760px]"><MailDesktopHeader /><div className="flex min-h-[500px]"><MailDesktopSidebar /><section className="min-w-0 flex-1"><div className="flex items-center justify-between border-b border-[#e0e7ef] bg-[#f8fafc] px-4 py-2.5"><div className="flex items-center gap-2"><button className="rounded-sm border border-[#d6e1ee] bg-white px-3 py-1.5 font-sans text-xs text-[#526a83]">全部邮件</button><button className="rounded-sm border border-[#d6e1ee] bg-white px-3 py-1.5 font-sans text-xs text-[#526a83]">标记已读</button><button className="rounded-sm border border-[#d6e1ee] bg-white px-3 py-1.5 font-sans text-xs text-[#526a83]">更多 <ChevronDown className="ml-1 inline h-3 w-3" /></button></div><span className="font-mono text-[10px] text-[#8b9aac]">邮件 1-{totalMessages} / {totalMessages}</span></div><div className="grid grid-cols-[minmax(0,1fr)_120px] gap-3 border-b border-[#dbe4ee] bg-[#f4f7fb] px-5 py-2 font-mono text-[9px] tracking-[.1em] text-[#8798aa]"><span>发件人 / 主题</span><span className="text-right">时间</span></div><button type="button" onClick={onOpen} className="grid w-full grid-cols-[minmax(0,1fr)_120px] gap-3 border-b border-[#dce5ee] bg-[#fffdf7] px-5 py-4 text-left transition hover:bg-[#fff7dc]"><span className="min-w-0"><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#e5a636]" /><b className="truncate font-sans text-sm text-[#294d6d]">{inbox.senderName}</b><span className="rounded-sm bg-[#fff0c8] px-1.5 py-0.5 font-mono text-[9px] text-[#9a701f]">外部</span></span><span className="mt-1 block truncate font-sans text-xs text-[#486783]">{inbox.subject}</span><span className="mt-1 flex items-center gap-1 font-mono text-[10px] text-[#9b7b42]"><FileText className="h-3 w-3" /> {inbox.attachment.displayName} · {inbox.attachment.metadata}</span></span><span className="pt-0.5 text-right font-mono text-[10px] text-[#819499]">{inbox.receivedAt}</span></button>{routineMessages.map(({ sender, subject, time }) => <div key={sender} className="grid grid-cols-[minmax(0,1fr)_120px] gap-3 border-b border-[#edf1f5] px-5 py-3.5"><span className="min-w-0"><span className="block truncate font-sans text-xs font-medium text-[#526c84]">{sender}</span><span className="mt-1 block truncate font-sans text-[11px] text-[#8193a4]">{subject}</span></span><span className="text-right font-mono text-[10px] text-[#9aa9b5]">{time}</span></div>)}</section></div><div className="border-t border-[#dce5ee] bg-[#f7f9fc] px-4 py-2.5 font-sans text-[10px] text-[#7e91a4]">教学提示：请通过完整地址、回复地址、附件与业务流程判断邮件可信度。</div></div></div>;
}
